### ISSUE TITLE
Why this application needs access to home?

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.gnome.Eolie#15]
Hi,

I noticed that this application has rw access to whole home and also rw access to:
```
 ~/.config/chrome
 ~/.config/chromium
 ~/.config/dconf
 ~/.mozilla/firefox
```

Why is this needed?

**Comment by bilelmoussaoui** [comment]
The dconf is needed for gsettings of the application itself. There's a WIP to add a portal for that so this could be removed in the future. 

The access to the whole home is to allow you to download and save those files to a specific location. The app should use NativeFileChooser which uses a portal. It should be reported here in order to get that fixed https://gitlab.gnome.org/World/eolie

The .config/{chrome/chromium/firefox}  is used to import bookmarks from those browsers.

**Comment by Zlopez** [comment]
> The access to the whole home is to allow you to download and save those files to a specific location.

I don't think it is wise to give the flatpak full home access just because someone wants to save downloaded files to other directory than xdg-download. But you're right that using a NativeFileChooser portal for this is a good idea, I will create a issue for this on https://gitlab.gnome.org/World/eolie


> The .config/{chrome/chromium/firefox} is used to import bookmarks from those browsers.

The read-only access should be sufficient for this, not full read-write access.

**Comment by Zlopez** [comment]
Reported https://gitlab.gnome.org/World/eolie/issues/321

**Comment by loupianche** [comment]
Lollypop already uses Gtk.FileChooserNative

**Comment by bilelmoussaoui** [comment]
It's not a Lollypop issue here.

**Comment by loupianche** [comment]
Oops :-)
In fact, Eolie uses Gtk.FileChooserNative as possible.
- WebKitGTK needs this access: "--filesystem=xdg-download" for epiphany but Eolie allows any path.
- Images/Videos download does not use a dialog and needs this access

**Comment by bilelmoussaoui** [comment]
So right now which permissions should be used?

**Comment by bilelmoussaoui** [comment]
@nedrichards Can you give @loupianche write access to Eolie & Lollypop, please? Thanks :+1:

**Comment by loupianche** [comment]
@bilelmoussaoui No changes for now.
